development:
  :address: smtp.gmail.com
  :port: 587
  :Domain: mail.google.com
  :authentication: plain
  :user_name: info@calgaryserviceplumbers.com
  :password: welcome123
  :enable_starttls_auto: true        

production:
  :address: smtp.gmail.com
  :port: 587
  :Domain: mail.google.com
  :authentication: plain
  :user_name: info@calgaryserviceplumbers.com
  :password: welcome123
  :enable_starttls_auto: true 
